### ISSUE TITLE
ERROR: IllegalStateException: nx-repository-view-conda-*-read already exists

### ISSUE THREAD

**Issue by cniweb** [kbc-opensource/nexus-conda-plugin#3]
We have an issue when using Sonatype Nexus Repository PRO version **3.66.0-02**.
The following error message appears at startup and Nexus closes again:
`ERROR [qtp550111516-692]  *UNKNOWN org.sonatype.nexus.extdirect.internal.ExtDirectExceptionHandler - Failed to invoke action method: rapture_Security.getPermissions, java-method: org.sonatype.nexus.rapture.internal.security.SecurityComponent.getPermissions
java.lang.IllegalStateException: nx-repository-view-conda-*-read already exists `

**Comment by cniweb** [comment]
@wimvanleuven-kbc or @petewil unfortunately, your plugin does not work with version 3.69.0 either. Could someone of you please take a look at this? We need the plugin or compatibility with future Nexus versions.
Big thanks 🙏🏼

**Comment by bartdevriendt** [comment]
@cniweb 

I uploaded a new version that works for us.  You need to disable the default nexus conda plugin as stated in the readme.
